name: Tag Example with branch check action

on:
  push:
    tags:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          echo "raw is $raw"
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_ENV
          echo "Branch is $branch."
      
      - name: Check branch
        run: |
          if [ ${{ steps.check_step.outputs.branch }} == "main" ]; then
            echo "Branch is main"
          else
            echo "Branch is not main"
          fi
