# This only runs for tags, and the job only processes for "master" branch
name: Tag Example with branch check

on:
  workflow_dispatch:

  push:
    branches:
      - main
    if: |
      (startsWith(github.ref, 'refs/tags/')) || 
      (!startsWith(github.ref, 'refs/tags/')


jobs:
  check-current-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Fetch all tags
        run: git fetch --all --tags

      - name: Show all tags
        run: git tag -l


