# This only runs for tags, and the job only processes for "master" branch
name: Tag Example with branch check

on:
  push:
    tags:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set branch name as output
        id: set_branch
        run: echo "The branch name is ${{ steps.branch.outputs.branch }}"
      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."

  job1:
    runs-on: ubuntu-latest
    needs: check # Wait for check step to finish
    if: ${{ needs.check.outputs.branch == 'main' }} # only run if branch is main
    steps:
      - run: echo ${{ needs.check.outputs.branch}}

  job2:
    runs-on: ubuntu-latest
    needs: check # Wait for check step to finish
    if: ${{ needs.check.outputs.branch == 'main' }} # only run if branch is master

    steps:
      - run: echo "Running task..."
