# This only runs for tags, and the job only processes for "master" branch
name: Tag Example with branch check

on:
  workflow_dispatch:

  push:
    tags:
      - "*"


jobs:
  check-current-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Fetch all tags
        run: git fetch --all --tags

      - name: Show all tags
        run: git tag -l


