# This only runs for tags, and the job only processes for "master" branch
name: Tag Example with branch check

on:
  push:
    tags:
      - "*"

jobs:
  # @see https://stackoverflow.com/a/72959712/8179249
  check-current-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        # 1. Get the list of branches ref where this tag exists
        # 2. Remove 'origin/' from that result
        # 3. Put that string in output
        # => We can now use function 'contains(list, item)''
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "{name}=b  ranch" >> $GITHUB_ENV
          echo "Branches where this tag exists : $branch."
      
      - name: Echo if branch name is main
        if: contains(${{ steps.check_step.outputs.branch }}, 'main')
        run: echo "Branch is main"

