name: Fedora-Dnf-Test
on: [push, pull_request, workflow_dispatch]

jobs:
  fedora-python-tox:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - name: Fedora dnf update
        run: dnf update -y 
      - name: Install tox
        run: dnf install tox -y
