name: Test slash commands 

on:
  issue_comment:
    types: [created]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.issue.number || github.ref }}
    cancel-in-progress: true

jobs:
  ci-job:
    if: startsWith(github.event.comment.body, '/start') && github.event.issue.pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Extract number
      id: extract-number
      run: |
        NUMBER=$(echo "${{ github.event.comment.body }}" | awk -F' ' '{print $2}')
        echo "::set-output name=number::$NUMBER"

    - name: Extract number2
      run: echo "::set-output name=number::$NUMBER"
      
    - name: Comment number to related issue
      uses: actions/github-script@v5
      with:
        script: |
          const issue_number = context.issue.number;
          const number = "${{ steps.extract-number.outputs.number }}";
          const message = `The extracted number is ${number}`;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: message
          });
